version: '3'

services:

  url-shorten-app:
    image: url-shorten-app:latest
    build:
      context: urlshortenapp
      dockerfile: Dockerfile
    depends_on:
      - url-shorten-elasticsearch
      - key-gen-svc
    environment:
      ELASTICSEARCH_ADDRESSES: http://url-shorten-elasticsearch:9200
      ELASTICSEARCH_INDEX: urlstore
      INIT_MAXIMUM_ATTEMPTS: 6
      INIT_WAIT_IN_SECONDS: 10
      INTERNAL_SHORT_HOST: http://localhost:8080
      KEYGENSVC_URL: http://key-gen-svc:5000
      MAXIMUM_SHORT_URL_PATH_LENGTH: 12
      MINIMUM_SHORT_URL_PATH_LENGTH: 6
    ports:
      - "8080:80"

  url-shorten-elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      node.name: es01
      cluster.initial_master_nodes: es01
      cluster.name: es-local-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  key-gen-svc:
    image: key-gen-svc:latest
    build:
      context: keygensvc
      dockerfile: Dockerfile
    depends_on:
      - key-gen-postgres
    environment:
      POSTGRES_CONNECTION_STRING:
        postgres://postgres@key-gen-postgres:5432/keystore?sslmode=disable
      MAXIMUM_KEY_LENGTH: 36
      MINIMUM_KEY_LENGTH: 6
      MINIMUM_SOURCE_NAME_LENGTH: 4
    ports:
      - "5000:5000"
    volumes:
      - ./keygensvc/db:/keygensvc/db

  key-gen-postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: keystore
      POSTGRES_HOST_AUTH_METHOD: trust  # Ease local dev. Prod requires password.
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
